export const circs = [
    {
        title: 'Australia',
        img: require('../images/circuits/australia2.png'),
        circuitMap: require('../images/circuits/australia.png'),
        link: 'CircuitTime',
        document: 'Australia',
    },
    {
        title: 'Bahrain',
        img: require('../images/circuits/Bahrain2.png'),
        circuitMap: require('../images/circuits/bahrain.png'),
        link: 'CircuitTime',
        document: 'Bahrain',
    },
    {
        title: 'China',
        img: require('../images/circuits/China2.png'),
        circuitMap: require('../images/circuits/China.png'),
        link: 'CircuitTime',
        document: 'China',
    },
    {
        title: 'Azerbijan',
        img: require('../images/circuits/azerbijan2.png'),
        circuitMap: require('../images/circuits/azerbijan.png'),
        link: 'CircuitTime',
        document: 'Azerbijan',
    },
    {
        title: 'Spain',
        img: require('../images/circuits/spain2.png'),
        circuitMap: require('../images/circuits/spain.png'),
        link: 'CircuitTime',
        document: 'Spain',
    },
    {
        title: 'Monaco',
        img: require('../images/circuits/monaco2.png'),
        circuitMap: require('../images/circuits/monaco.png'),
        link: 'CircuitTime',
        document: 'Monaco',
    },
    {
        title: 'Canada',
        img: require('../images/circuits/canada2.png'),
        circuitMap: require('../images/circuits/canada.png'),
        link: 'CircuitTime',
        document: 'Canada',
    },
    {
        title: 'France',
        img: require('../images/circuits/france2.png'),
        circuitMap: require('../images/circuits/france.png'),
        link: 'CircuitTime',
        document: 'France',
    },
    {
        title: 'Austria',
        img: require('../images/circuits/austria2.png'),
        circuitMap: require('../images/circuits/austria.png'),
        link: 'CircuitTime',
        document: 'Austria',
    },
    {
        title: 'Great Britain',
        img: require('../images/circuits/brit2.png'),
        circuitMap: require('../images/circuits/brit.png'),
        link: 'CircuitTime',
        document: 'Great Britain',
    },
    {
        title: 'Germany',
        img: require('../images/circuits/germany2.png'),
        circuitMap: require('../images/circuits/germany.png'),
        link: 'CircuitTime',
        document: 'Germany',
    },
    {
        title: 'Hungary',
        img: require('../images/circuits/hungary2.png'),
        circuitMap: require('../images/circuits/hungary.png'),
        link: 'CircuitTime',
        document: 'Hungary',
    },
    {
        title: 'Belgium',
        img: require('../images/circuits/belgium2.png'),
        circuitMap: require('../images/circuits/belgium.png'),
        link: 'CircuitTime',
        document: 'Belgium',
    },
    {
        title: 'Italy',
        img: require('../images/circuits/italy2.png'),
        circuitMap: require('../images/circuits/italy.png'),
        link: 'CircuitTime',
        document: 'Italy',
    },
    {
        title: 'Singapore',
        img: require('../images/circuits/singapore2.png'),
        circuitMap: require('../images/circuits/singapore.png'),
        link: 'CircuitTime',
        document: 'Singapore',
    },
    {
        title: 'Russia',
        img: require('../images/circuits/russia2.png'),
        circuitMap: require('../images/circuits/russia.png'),
        link: 'CircuitTime',
        document: 'Russia',
    },
    {
        title: 'Japan',
        img: require('../images/circuits/japan2.png'),
        circuitMap: require('../images/circuits/japan.png'),
        link: 'CircuitTime',
        document: 'Japan',
    },
    {
        title: 'Mexico',
        img: require('../images/circuits/mexico2.png'),
        circuitMap: require('../images/circuits/mexico.png'),
        link: 'CircuitTime',
        document: 'Mexico',
    },
    {
        title: 'United States',
        img: require('../images/circuits/unitedstates2.png'),
        circuitMap: require('../images/circuits/unitedstates.png'),
        link: 'CircuitTime',
        document: 'United States',
    },
    {
        title: 'Brazil',
        img: require('../images/circuits/brazil2.png'),
        circuitMap: require('../images/circuits/brazil.png'),
        link: 'CircuitTime',
        document: 'Brazil',
    },
    {
        title: 'Abu Dhabi',
        img: require('../images/circuits/abudhabi2.png'),
        circuitMap: require('../images/circuits/abudhabi.png'),
        link: 'CircuitTime',
        document: 'Abu Dhabi',
    },
];
