export const circs = [
    {
        title: 'Australia',
        circuitName: 'Albert Park Street Circuit',
        img: require('../images/backgrounds/melbourneImg.jpg'),
        circuitMap: require('../images/circuits/australia.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Australia',
    },
    {
        title: 'Bahrain',
        circuitName: 'Barhain International Circuit',
        img: require('../images/backgrounds/bahrain.jpg'),
        circuitMap: require('../images/circuits/bahrain.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Bahrain',
    },
    {
        title: 'China',
        circuitName: 'Shanghai International Circuit',
        img: require('../images/backgrounds/china.jpg'),
        circuitMap: require('../images/circuits/China.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'China',
    },
    {
        title: 'Azerbijan',
        circuitName: 'Baku City circuit',
        img: require('../images/backgrounds/azerbijan.jpg'),
        circuitMap: require('../images/circuits/azerbijan.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Azerbijan',
    },
    {
        title: 'Spain',
        circuitName: 'Circuit de Barcelona-Catalunya',
        img: require('../images/backgrounds/spain.jpg'),
        circuitMap: require('../images/circuits/spain.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Spain',
    },
    {
        title: 'Monaco',
        circuitName: 'Circuit de Monaco',
        img: require('../images/backgrounds/monaco.jpg'),
        circuitMap: require('../images/circuits/monaco.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Monaco',
    },
    {
        title: 'Canada',
        circuitName: 'Circuit Gilles Villeneuve',
        img: require('../images/backgrounds/canada.jpg'),
        circuitMap: require('../images/circuits/canada.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Canada',
    },
    {
        title: 'France',
        circuitName: 'Circuit Paul Ricard',
        img: require('../images/backgrounds/france.jpg'),
        circuitMap: require('../images/circuits/france.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'France',
    },
    {
        title: 'Austria',
        circuitName: 'Red Bull Ring',
        img: require('../images/backgrounds/austria.jpg'),
        circuitMap: require('../images/circuits/austria.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Austria',
    },
    {
        title: 'UK',
        circuitName: 'Silverstone',
        img: require('../images/backgrounds/greatbrittain.jpg'),
        circuitMap: require('../images/circuits/brit.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Great Britain',
    },
    {
        title: 'Germany',
        circuitName: 'Hockenheim',
        img: require('../images/backgrounds/germany.jpg'),
        circuitMap: require('../images/circuits/germany.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Germany',
    },
    {
        title: 'Hungary',
        circuitName: 'Hungaroring',
        img: require('../images/backgrounds/hungary.jpg'),
        circuitMap: require('../images/circuits/hungary.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Hungary',
    },
    {
        title: 'Belgium',
        circuitName: 'Spa-Francorchamps',
        img: require('../images/backgrounds/belgium.jpg'),
        circuitMap: require('../images/circuits/belgium.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Belgium',
    },
    {
        title: 'Italy',
        circuitName: 'Autodromo Nazionale Monza',
        img: require('../images/backgrounds/italy.jpg'),
        circuitMap: require('../images/circuits/italy.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Italy',
    },
    {
        title: 'Singapore',
        circuitName: 'Marina Bay',
        img: require('../images/backgrounds/singapore.jpg'),
        circuitMap: require('../images/circuits/singapore.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Singapore',
    },
    {
        title: 'Russia',
        circuitName: 'Sochi Autodrom',
        img: require('../images/backgrounds/russia.jpeg'),
        circuitMap: require('../images/circuits/russia.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Russia',
    },
    {
        title: 'Japan',
        circuitName: 'Suzuka',
        img: require('../images/backgrounds/japan.jpeg'),
        circuitMap: require('../images/circuits/japan.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Japan',
    },
    {
        title: 'Mexico',
        circuitName: 'Autódromo Hermanos Rodríguez',
        img: require('../images/backgrounds/mexico.jpg'),
        circuitMap: require('../images/circuits/mexico.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Mexico',
    },
    {
        title: 'America',
        circuitName: 'Circuit of the Americas',
        img: require('../images/backgrounds/mexico.jpeg'),
        circuitMap: require('../images/circuits/unitedstates.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'United States',
    },
    {
        title: 'Brazil',
        circuitName: 'Interlagos',
        img: require('../images/backgrounds/brazil.jpg'),
        circuitMap: require('../images/circuits/brazil.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Brazil',
    },
    {
        title: 'Abu Dhabi',
        circuitName: 'Yas Marina Circuit',
        img: require('../images/backgrounds/abudhabi.jpg'),
        circuitMap: require('../images/circuits/abudhabi.png'),
        link: 'CircuitTime',
        linknoline: 'CircuitTimeNoLine',
        document: 'Abu Dhabi',
    },
];
